// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordeon': string;
  'acorBody': string;
  'code': string;
  'fileInput': string;
  'message': string;
  'saveBlock': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
